### ISSUE TITLE
Need ability to exclude sourceSets by name.

### ISSUE THREAD

**Issue by ysb33r** [hierynomus/license-gradle-plugin#115]
This is affecting users of GradleTest 1.0 already even though it is only in beta atm. The issue however is not restricted to GradleTest, it affects any scenario where sourceSets include generated source and such source might already contain license headers which differ from the project standard ones. 

THe best solution would be to have a wat of saying to exclude certain sourceSets by name. (Curretnly the workaround is to eithe rlist the path where the generated code goes to or use a pattern which hopefully does not match with anything in another sourceSet).

**Comment by hierynomus** [comment]
The plugin is now split up into `com.github.hierynomus.license-base` and `com.github.hierynomus.license`.
The `license-base` plugin only adds the tasks to each sourceset, but does not actually hook them up into the lifecycle.
The `license` plugin is opinionated and hooks up the tasks created by the `license-base` plugin to the `check` lifecycle.

I think this fixes you problem, since now you can just apply the `license-base` plugin and only configure the tasks you want to have added to the gradle lifecycle, foregoing the tasks that operate on the generated sourceSets.

**Comment by grv87** [comment]
Why generated sources are even placed in regular `src` directory? There is `build/generated` directory for that.
