### ISSUE TITLE
Empty report with android multi module project

### ISSUE THREAD

**Issue by emartynov** [hierynomus/license-gradle-plugin#81]
I'm trying to include your plugin to our project automation:
```
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.0'
        classpath 'nl.javadude.gradle.plugins:license-gradle-plugin:0.11.0'
    }
}

allprojects {
    apply plugin: 'com.github.hierynomus.license'
}
```

I see empty license report after running `downloadLicenses` task.
I see also next output when run it with debug flag:
```
[DEBUG] [nl.javadude.gradle.plugins.license.LicenseResolver] Project app found 0 dependencies to handle.
```

Please help to fix it

**Comment by hierynomus** [comment]
Have you got it to work on a single module?

**Comment by emartynov** [comment]
I have no effect if I just run `app:downloadLicenses`. I use gradle 2.6

**Comment by atakankaya** [comment]
The documentation of the license task states that it will default to all sourceSets created by Java Plugin.

And I cannot see a property for downloadLicenses task, could it be because of that?

**Comment by hierynomus** [comment]
Do you have a sample project setup somewhere? Or could you add a test in a PR? I'd be happy to look at it

**Comment by fweigl** [comment]
Since this is still open, I can not get a proper license report for the most simple (one module) Android project. 
I've created an example here: https://bitbucket.org/asco33/licensetest

I have just added the classpath dependency (to the top level build.gradle) and the 'apply plugin' part to the module build.gradle. Running gradle downloadDependencies creates an empty report. 

I know I am missing something to get this to work, but am too inept to see what and where exactly (not good with gradle and groovy :( ). 

Can you point me in the right direction?

**Comment by hierynomus** [comment]
Have you tried using the latest version (0.12.1)?

**Comment by fweigl** [comment]
Thanks for taking the time. 
I did just now, same effect. I updated the example project to reflect that.

**Comment by hierynomus** [comment]
Cool! I think that means that this can be closed now?
Just to check you're using a multi module project, right?

**Comment by fweigl** [comment]
The example project was single-module but the plugin for me also works fine on a multi-module project.

**Comment by hierynomus** [comment]
Cool. I'll close this one then as solved. The latest version and a `downloadLicenses {...}` closure work for an android project.

**Comment by hierynomus** [comment]
Thanks!
